name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build app
        run: npm run build
      - uses: actions/checkout@v2
      - name: Delete Old Site
        run: rm -rf docs
      - name: Change "dist" to "docs"
        run: mv dist docs
      - name: Add site details to CNAME
        run: echo kilkenny.dev > docs/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
