name: CI

on:
  workflow_run:
    workflows: ["Check Master for Build"]
    branches: [master]
    types: 
      - completed

jobs:

  on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - run: echo "Check on Master branch has passed!"
  setup:
    runs-on: ubuntu-latest
    needs: on-success
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build app
        run: npm run build
      - name: Add site details to CNAME
        run: echo kilkenny.dev > dist/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
