name: Merge changes to other branches

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Get all branches except master
        id: get_branches
        run: |
          BRANCHES=$(git branch -r | grep -v '\->' | grep -v 'master$' | sed 's/origin\///')
          if [ -z "$BRANCHES" ]; then
            echo "No branches to update."
            exit 0
          fi
          echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Merge master into all branches
        if: steps.get_branches.outputs.branches != ''
        run: |
          for branch in ${{ steps.get_branches.outputs.branches }}; do
            git checkout $branch
            git merge master || true  # Continue even if merge conflicts arise
            git push origin $branch
          done
